name: cozy-salt
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pyyaml
  - jq
  - shellcheck
  - pip-tools
  - pip:
      - salt
      - salt-lint
      - yamllint
      - pylint
      - ruff
      - isort
      - pytest
      - pytest-cov
      - jinja2
      - pre-commit
