"$schema" = 'https://starship.rs/config-schema.json'

# =========================================================================== #
# PROFILE
# Reference: https://starship.rs/config/
# =========================================================================== #

palette = "Twilite_Darker"

right_format = "[$time]($style) [$jobs]($style) [$battery]($style)"

format = """\
$localip\
$docker_context\
$kubernetes\
$direnv\
$shell\
$line_break\
$all\
$line_break\
$character \
"""

add_newline = true

[line_break]
disabled = false

[character]
success_symbol = "[âœ](bold green)"
error_symbol   = "[âœ—](bold red)"

[cmd_duration]
style = "bold yellow"

[username]
format = "[$user]($style) "
style_user = "bold cyan"

[hostname]
style = "bold purple"

[directory]
read_only = " ó°Œ¾ "
style = "bold green"

# =========================================================================== #
# system
# =========================================================================== #

[battery]
full_symbol = "ğŸ”‹ "
charging_symbol = "âš¡ï¸ "
discharging_symbol = "ğŸ’€ "
style = "bold yellow"

[container]
format = '[$symbol \[$name\]]($style) '
symbol = " â¬¢ "
style = "bold red"

[docker_context]
symbol = " ïŒˆ "
style = "bold green"
only_with_files = false

[fill]
symbol = " . "
style = "bold black"

[jobs]
symbol = " âœ¦ "
number_threshold = 4
symbol_threshold = 0
style = "bold blue"

[memory_usage]
symbol = " ó°› "
style = "bold red"

[status]
symbol = " ï‘§ "
style = "bold red"

[time]
format = "ğŸ•™[ $time ]($style) "
time_format = "%T"
style = "bold dimmed white"

[shell]
powershell_indicator = "psh"
pwsh_indicator = "pwsh"
bash_indicator = "bash"
zsh_indicator = "zsh"
format = "[$indicator]($style) "
style = "cyan bold"
disabled = false

# =========================================================================== #
# scm
# =========================================================================== #

[git_branch]
symbol = " ï˜ "
style = "bold pink"

[git_commit]
tag_symbol = " ï’ "
style = "bold pink"

[git_metrics]
added_style = "bold green"
deleted_style = "bold red"
format = "([+$added]($added_style) )([-$deleted]($deleted_style) )"
disabled = true

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bold yellow"

[git_status]
style = "bold red"

# =========================================================================== #
# platform
# =========================================================================== #

[aws]
symbol = " îŒ½ "
style = "bold purple"
format = "[$symbol ]($style)"

[gcloud]
symbol = " îŸ± "
style = "bold purple"

[kubernetes]
disabled = false
symbol = " âˆ "
style = "bold brightPurple"
format = '[$symbol$context(\($namespace\))]($style) '
contexts = [
	{ context_pattern = ".*(dev|test).*", style = "bold brightGreen", symbol = "âš™ï¸" },
	{ context_pattern = ".*staging.*", style = "bold brightYellow", symbol = " ğŸŸ¡ " },
	{ context_pattern = ".*prod.*", style = "bold brightRed", symbol = " ğŸ”¥ " }
]

[localip]
disabled = false
ssh_only = false
format = 'ğŸ“¡ [$localipv4]($style) '
style = "bold brightYellow"

[direnv]
disabled = false
symbol = " ğŸŒ¿ "
style = "bold green"
format = '[$symbol$loaded]($style) '

# =========================================================================== #
# version management
# =========================================================================== #

[conda]
symbol = " â—‰ "
style = "bold yellow"
ignore_base = false
format = "[$symbol$environment ]($style)"


[nix_shell]
symbol = " ïŒ“ "
style = "bold green"

# =========================================================================== #
# language
# =========================================================================== #

[buf]
symbol = " ï’ "
style = "bold green"
format = "[$symbol ]($style)"

[bun]
symbol = " î¯ "
style = "bold green"
format = "[$symbol ]($style)"

[c]
symbol = " î˜ "
style = "bold cyan"
format = "[$symbol$version ]($style)"

[cmake]
symbol = " î” "
style = "bold red"
format = "[$symbol ]($style)"

[cpp]
symbol = " î˜ "
style = "bold cyan"
format = "[$symbol$version ]($style)"

[crystal]
symbol = " î˜¯ "
style = "bold cyan"
format = "[$symbol$version ]($style)"

[dart]
symbol = " î˜ "
style = "bold cyan"
format = "[$symbol$version ]($style)"

[deno]
symbol = " îŸ€ "
style = "bold cyan"
format = "[$symbol$version ]($style)"

[elixir]
symbol = " î˜­ "
style = "bold cyan"
format = "[$symbol$version ]($style)"

[elm]
symbol = " î˜¬ "
style = "bold cyan"
format = "[$symbol$version ]($style)"

[fennel]
symbol = " îš¯ "
style = "bold cyan"
format = "[$symbol$version ]($style)"

[fortran]
symbol = " îŸ "
style = "bold cyan"
format = "[$symbol$version ]($style)"

[fossil_branch]
symbol = " ï˜ "
style = "bold pink"
format = "[$symbol ]($style)"

[golang]
symbol = " î˜§ "
style = "bold cyan"
format = "[$symbol$version ]($style)"

[gradle]
symbol = " î™  "
style = "bold red"

[guix_shell]
symbol = " ïŒ¥ "
style = "bold green"

[haskell]
symbol = " î· "
style = "bold cyan"
format = "[$symbol$version ]($style)"

[haxe]
symbol = " î™¦ "
style = "bold cyan"
format = "[$symbol$version ]($style)"

[hg_branch]
symbol = " ï˜ "
style = "bold pink"

[java]
symbol = " î‰– "
style = "bold cyan"
format = "[$symbol$version ]($style)"

[julia]
symbol = " î˜¤ "
style = "bold cyan"
format = "[$symbol$version ]($style)"

[kotlin]
symbol = " î˜´ "
style = "bold cyan"
format = "[$symbol$version ]($style)"

[lua]
symbol = " î˜  "
style = "bold cyan"
format = "[$symbol$version ]($style)"

[meson]
symbol = " ó°”· "
style = "bold red"

[nim]
symbol = " ó°†¥ "
style = "bold cyan"
format = "[$symbol$version ]($style)"

[nodejs]
symbol = " îœ˜ "
style = "bold green"
format = "[$symbol$version ]($style)"

[ocaml]
symbol = " î™º "
style = "bold cyan"
format = "[$symbol$version ]($style)"

[package]
symbol = " ó°— "
style = "bold yellow"

[perl]
symbol = " î™¾ "
style = "bold cyan"
format = "[$symbol$version ]($style)"

[php]
symbol = "   "
style = "bold cyan"
format = "[$symbol$version ]($style)"

[pixi]
symbol = " ó°— "
style = "bold yellow"

[python]
symbol = " îˆµ "
style = "bold purple"
format = "[$symbol$version ]($style)"

[rlang]
symbol = " ó°Ÿ” "
style = "bold cyan"
format = "[$symbol$version ]($style)"

[ruby]
symbol = " î‘ "
style = "bold cyan"
format = "[$symbol$version ]($style)"

[rust]
symbol = " ó±˜— "
style = "bold purple"
format = "[$symbol$version ]($style)"

[scala]
symbol = " îœ· "
style = "bold cyan"
format = "[$symbol$version ]($style)"

[swift]
symbol = " î• "
style = "bold cyan"
format = "[$symbol$version ]($style)"

[xmake]
symbol = " î” "
style = "bold red"

[zig]
symbol = " îš© "
style = "bold cyan"
format = "[$symbol$version ]($style)"

# =========================================================================== #
# os
# =========================================================================== #

[os.symbols]
Alpaquita = " îª¢ "
Alpine = " ïŒ€ "
AlmaLinux = " ïŒ "
Amazon = " ï‰° "
Android = " ï…» "
AOSC = " ïŒ "
Arch = " ïŒƒ "
Artix = " ïŒŸ "
CachyOS = " ïŒƒ "
CentOS = " ïŒ„ "
Debian = " ïŒ† "
DragonFly = " îŠ "
Emscripten = " ïˆ… "
EndeavourOS = " ï†— "
Fedora = " ïŒŠ "
FreeBSD = " ïŒŒ "
Garuda = " ó°›“ "
Gentoo = " ïŒ "
HardenedBSD = " ó°Œ "
Illumos = " ó°ˆ¸ "
Kali = " ïŒ§ "
Linux = " ïŒš "
Mabox = " î¬© "
Macos = " ïŒ‚ "
Manjaro = " ïŒ’ "
Mariner = " ï‡ "
MidnightBSD = " ï†† "
Mint = " ïŒ "
NetBSD = " ï€¤ "
NixOS = " ïŒ“ "
Nobara = " ï€ "
OpenBSD = " ó°ˆº "
openSUSE = " ïŒ” "
OracleLinux = " ó°Œ· "
Pop = " ïŒª "
Raspbian = " ïŒ• "
Redhat = " ïŒ– "
RedHatEnterprise = " ïŒ– "
RockyLinux = " ïŒ« "
Redox = " ó°€˜ "
Solus = " ó° ³ "
SUSE = " ïŒ” "
Ubuntu = " ïŒ› "
Unknown = " ïˆ­ "
Void = " ïŒ® "
Windows = " ó°² "

# =========================================================================== #
# colour palettes
# =========================================================================== #

[palettes.Twilite]
background = "#18152a"
current_line = "#44475a"
foreground = "#d8d8d8"
comment = "#44475a"
black = "#282a36"
blue = "#a080d9"
cyan = "#70c9dd"
green = "#40d860"
purple = "#d960a8"
red = "#d84040"
white = "#a0a0a0"
yellow = "#d0d870"
brightBlack = "#44475a"
brightBlue = "#b89ae0"
brightCyan = "#88dde8"
brightGreen = "#58e878"
brightPurple = "#e878c0"
brightRed = "#e85858"
brightWhite = "#e8e8e8"
brightYellow = "#e0e888"
cursor = "#ff79c6"
selection = "#44475a"

[palettes.Twilite_Darker]
background = "#141025"
foreground = "#F8F8F2"
black = "#21222c"
blue = "#b084f5"
cyan = "#79ddf0"
green = "#40e868"
purple = "#f060b3"
red = "#e84545"
white = "#a8a8a8"
yellow = "#e0e878"
brightBlack = "#4d5066"
brightBlue = "#d4b5ff"
brightCyan = "#b8ffff"
brightGreen = "#7dffaa"
brightPurple = "#ffa8eb"
brightRed = "#ff8080"
brightWhite = "#ffffff"
brightYellow = "#ffffb8"
cursor = "#ff79c6"
selection = "#44475a"
